<?php
	require_once('Database.php');
	
	class Post_model extends Database {
		public function savePost($data) {
            $stmt = $this->conn->prepare("INSERT INTO posts (id, created_time, message, picture, likes, comments, auto_generated) VALUES (?, ?, ?, ?, ?, ?, ?)");
            $stmt->execute(array($data['id'], $data['created_time'], $data['message'], $data['picture'], $data['likes'], $data['comments'], $data['auto_generated']));
        }
		
		public function getAutoGeneratedPosts() {
			$stmt = $this->conn->prepare("SELECT id FROM posts WHERE auto_generated = 1");
            $stmt->execute();
			
            return $stmt->fetchAll(PDO::FETCH_ASSOC);
		}
		
		public function truncatePosts() {
			$stmt = $this->conn->prepare("TRUNCATE posts");
            $stmt->execute();
		}
	}
?>